- name: uninstall nginx
  hosts: frontend
  become: yes

  tasks:
    - name: remove nginx
      ansible.builtin.package:
        name: nginx
        state: absent

    - name: stop nginx service (safe cleanup)
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: no

