- name: variables from args
  hosts: local
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "course name is :{{ course }}, duration: {{duration}}, trainer: {{trainer}}"