- name: vars-preference
  hosts: local
  connection: local
  # vars_files:
  # - course.yaml
  vars_prompt:
  - name: name
    prompt: what is your name?
    private: false
  tasks:
  - name: testing variables preference
    # vars:
    #   name: from task level
    ansible.builtin.debug:
      msg: "name: {{ name }}"



# 1.first preference is args and command line
#2. from task level is second preference
#3. from files level is second preference
