- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest # item is a reserved keyword
    loop:
    - nginx
    - mysql
    - zip
