- name: functions
  hosts: local
  connection: local
  vars:
    technologies: devops,linux,shell,ansible #STRING
    tags:
      Application: payment
      Envinornment: dev
    listTags:
      - key: Application
        value: payment
      - key: Environment
        value: dev
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "hello, {{ name | default('Ramesh')}}" 

#string to list
  - name: convert string to list
    ansible.builtin.debug:
      msg: "technologies are: {{ technologies | split(',')}}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

  - name: convert list to map
    ansible.builtin.debug:
      msg: "Tags are: {{ listTags | items2dict }}"

  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file','00-student.yaml') | from_yaml}}"
  
  - name: convert yaml into json
    ansible.builtin.debug:
      msg: "json: {{ student_yaml | to_json  }}" 