- name: functions
  hosts: local
  connection: local
  vars:
    technologies: devops,linux,shell,ansible #STRING
    lower_string: raviteja
    upper_string: RAVITEJARAJU1999@GMAIL.COM
    ip: 100.53.214.38
    tags:
      Application: payment
      Envinornment: dev
    listTags:
      - key: Application
        value: payment
      - key: Environment
        value: dev
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "hello, {{ name | default('Ramesh')}}" 

#string to list
  - name: convert string to list
    ansible.builtin.debug:
      msg: "technologies are: {{ technologies | split(',')}}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags are: {{ tags | dict2items }}"

  - name: convert list to map
    ansible.builtin.debug:
      msg: "Tags are: {{ listTags | items2dict }}"

  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file','00-student.yaml') | from_yaml}}"
  
  - name: convert yaml into json
    ansible.builtin.debug:
      msg: "json: {{ student_yaml | to_json  }}"

  - name: save json to files
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json }}"

  - name: converting lower to upper
    ansible.builtin.debug:
      msg: "{{ lower_string  | upper}}"

  - name: converting UPPER to lower
    ansible.builtin.debug:
      msg: "{{ upper_string  | lower}}" 

  - name: check IP is valid or not
    ansible.builtin.debug: 
      msg: "{{ ip | ansible.utils.ipv4 }}"

  - name: grep for root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: command_output

  - name: print the command_output
    ansible.builtin.debug:
      msg: "{{ command_output }}"

  - name: redirects_output
    ansible.builtin.command: ls -ltr > /tmp/output.txt
    register: redirect_output
    ignore_errors: true

  - name: print redirect_output
    ansible.builtin.debug:
      msg: "{{ redirect_output }}"